project:
  type: book
  output-dir: docs

book:
  title: "My Digital Humanities Portfolio"
  author: "Loren Lee"
  date: "4/12/2025"
  chapters:
    - index.qmd
    - bio.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt



