project:
  type: book
  output-dir: docs

book:
  title: "My Digital Humanities Portfolio"
  author: "Loren Lee"
  date: "4/12/2025"
  chapters:
    - index.qmd
    - bio.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    number-sections: false
    include-in-header:
      - text:
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">

  pdf:
    documentclass: scrreprt



