# About this Portfolio

This portfolio presents my Digital Humanities work completed as part of the [DH Graduate Certificate Program](https://dh.virginia.edu/) at the University of Virginia. My primary areas of DH engagement have been digital editing and data visualization, two subfields that have shaped my approach to medieval manuscript studies and helped me develop [my dissertation](https://leeloren.github.io/dissertation/): a digital critical edition of *La Vie de sainte Marie l’Égyptienne* (Version T).

I first explored digital editing and translation by working on an excerpt of *Le Roman de Silence* through a course offered in my department on race, gender, and class in premodern France (Elective B), using the R package [bookdown](https://bookdown.org/yihui/bookdown/) to prototype my first ever digital edition. I later deepened these skills through extensive XML training and transcription work as a research assistant for my dissertation director, [Amy Ogden](https://french.as.virginia.edu/people/amy-ogden), in support of her [IATH-sponsored](https://www.iath.virginia.edu/) project [*Lives of the Saints: The Medieval French Hagiography Project*](https://frenchsaintslives.org/). My interest in data visualization further emerged through SARC 5400: Data Visualization (Elective A), where I studied tools like [Observable](https://observablehq.com/) and the theoretical work of [Edward Tufte](https://www.edwardtufte.com/). As a result of all my DH trainings, I've gained competencies in tools and languages like LaTeX, ArcGIS, Python, etc. And I’ve since integrated R into my regular research practice, using R to author Quarto books for both my dissertation and this very portfolio!

Throughout my time at UVA, I have also benefited from the many workshops, reading groups, and public lectures hosted by the Scholars’ Lab, and in support of the final year of my degree program, the SLab generously awarded me the 2024-2025 Digital Humanities Fellowship. I have done all I can to take full advantage of the wider DH community here at UVA, and I look forward to building on this foundation as I continue exploring the intersections between DH methods and manuscript studies.